version: "3.8"

services:
  backend:
    build:
      dockerfile: ./backend/Dockerfile
    env_file:
      - .env
    volumes:
      - ./backend:/opt/app/api

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
  frontend:
    image: node:latest
    working_dir: /app
    container_name: front
    volumes:
      - ./frontend:/app
    command: bash -c "npm install && npm run start"
    stdin_open: true

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend

volumes:
  postgres-db: